import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const interFont = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${interFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>        
        {children}
        <Footer/>

        <Toaster position="top-right" />
        </body>
    </html>
  );
}
